# Generated by Django 5.2.3 on 2025-06-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0002_initial_shifttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日付")),
                ("name", models.CharField(max_length=100, verbose_name="休日名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
            ],
            options={
                "verbose_name": "会社休日",
                "verbose_name_plural": "会社休日",
                "ordering": ["date"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "従業員", "verbose_name_plural": "従業員"},
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={"verbose_name": "シフト", "verbose_name_plural": "シフト"},
        ),
        migrations.AlterModelOptions(
            name="shifttype",
            options={"verbose_name": "シフト種別", "verbose_name_plural": "シフト種別"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, verbose_name="氏名"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="date",
            field=models.DateField(verbose_name="日付"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shift.employee",
                verbose_name="従業員",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shift.shifttype",
                verbose_name="シフト種別",
            ),
        ),
        migrations.AlterField(
            model_name="shifttype",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="シフト種別名"
            ),
        ),
    ]
