# Generated by Django 5.2.3 on 2025-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0003_companyholiday_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborLawSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_consecutive_work_days",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="連続勤務日数の上限",
                        verbose_name="最大連続勤務日数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "労働設定",
                "verbose_name_plural": "労働設定",
            },
        ),
        migrations.AddField(
            model_name="shifttype",
            name="is_work",
            field=models.BooleanField(
                default=True,
                help_text="休み以外の勤務日かどうか",
                verbose_name="勤務日",
            ),
        ),
    ]
