# Generated by Django 5.2.3 on 2025-06-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0004_laborlawsettings_shifttype_is_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborlawsettings",
            name="min_workers",
            field=models.PositiveIntegerField(
                default=1,
                help_text="1日に必要な最低労働者数（休み以外）",
                verbose_name="最低労働者数",
            ),
        ),
    ]
