# Generated by Django 5.2.3 on 2025-06-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0005_laborlawsettings_min_workers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"verbose_name": "シフト管理", "verbose_name_plural": "シフト管理"},
        ),
    ]
