# Generated by Django 5.2.3 on 2025-06-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0006_alter_shift_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"verbose_name": "シフト", "verbose_name_plural": "シフト"},
        ),
    ]
