# Generated by Django 5.2.3 on 2025-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0009_set_default_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttype",
            name="max_workers",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="このシフト種別の最大人数（設定しない場合は制限なし）",
                null=True,
                verbose_name="最大人数",
            ),
        ),
        migrations.AddField(
            model_name="shifttype",
            name="min_workers",
            field=models.PositiveIntegerField(
                default=1,
                help_text="このシフト種別に必要な最低人数",
                verbose_name="最低人数",
            ),
        ),
    ]
