# Generated by Django 5.2.3 on 2025-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0010_shifttype_max_workers_shifttype_min_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="役割名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
            ],
            options={
                "verbose_name": "役割",
                "verbose_name_plural": "役割",
            },
        ),
        migrations.AddField(
            model_name="shifttype",
            name="role_min_workers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="各役割の最低人数（例: {'ホール': 2, 'キッチン': 1}）",
                verbose_name="役割別最低人数",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="roles",
            field=models.ManyToManyField(
                blank=True, to="shift.role", verbose_name="役割"
            ),
        ),
    ]
