# Generated by Django 4.2.23 on 2025-06-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0011_role_shifttype_role_min_workers_employee_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shifttype",
            name="role_min_workers",
        ),
        migrations.CreateModel(
            name="ShiftTypeRoleMinWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_workers", models.PositiveIntegerField(default=0)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shift.role"
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_min_workers",
                        to="shift.shifttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "シフト種別役割別最低人数",
                "verbose_name_plural": "シフト種別役割別最低人数",
                "unique_together": {("shift_type", "role")},
            },
        ),
    ]
